import { useState, useCallback } from 'react';
import { motion } from 'framer-motion';
import { Sparkles, BookOpen, Code2, Lightbulb, FlaskConical, HelpCircle, ArrowRight } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { TopicInput } from '@/components/TopicInput';
import { LoadingSkeleton } from '@/components/LoadingSkeleton';
import { runPipeline, type PipelineProgress } from '@/ai/pipeline';
import type { LearningMaterial } from '@/types/learning';
import { toast } from '@/hooks/use-toast';

const FEATURES = [
  { icon: BookOpen, title: 'Smart Notes', description: 'Comprehensive study notes with key concepts' },
  { icon: Lightbulb, title: 'Simple Explanations', description: 'Complex topics made easy to understand' },
  { icon: Code2, title: 'Code Examples', description: 'Working implementations in multiple languages' },
  { icon: FlaskConical, title: 'Practical Examples', description: 'Real-world input/output demonstrations' },
  { icon: HelpCircle, title: 'Interactive Quiz', description: 'Test your understanding with quizzes' },
];

interface HomeProps {
  onMaterialGenerated: (material: LearningMaterial, topic: string) => void;
}

export function Home({ onMaterialGenerated }: HomeProps) {
  const [isLoading, setIsLoading] = useState(false);
  const [progress, setProgress] = useState<PipelineProgress>({ stage: '', progress: 0, message: '' });
  const navigate = useNavigate();

  const handleTopicSubmit = useCallback(async (topic: string) => {
    setIsLoading(true);
    setProgress({ stage: 'starting', progress: 0, message: 'Initializing AI pipeline...' });

    try {
      const material = await runPipeline(topic, (p) => {
        setProgress(p);
      });
      
      onMaterialGenerated(material, topic);
      
      toast({
        title: 'Learning materials ready!',
        description: `Generated comprehensive content for "${topic}"`,
      });
      
      navigate('/results');
    } catch (error) {
      toast({
        title: 'Generation failed',
        description: error instanceof Error ? error.message : 'An error occurred',
        variant: 'destructive',
      });
    } finally {
      setIsLoading(false);
    }
  }, [navigate, onMaterialGenerated]);

  return (
    <div className="min-h-screen">
      {/* Hero Section */}
      <section className="relative pt-20 pb-16 px-4 overflow-hidden">
        {/* Background Effects */}
        <div className="absolute inset-0 bg-hero-gradient opacity-50" />
        <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-primary/10 rounded-full blur-3xl" />
        <div className="absolute bottom-1/4 right-1/4 w-72 h-72 bg-accent/10 rounded-full blur-3xl" />
        
        <div className="relative max-w-4xl mx-auto text-center">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
          >
            <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-primary/10 border border-primary/20 mb-6">
              <Sparkles className="w-4 h-4 text-primary" />
              <span className="text-sm text-primary font-medium">AI-Powered Learning</span>
            </div>
            
            <h1 className="text-4xl md:text-6xl font-bold text-foreground mb-6 leading-tight">
              Learn Any Topic with
              <span className="block gradient-text glow-text">AI-Generated Content</span>
            </h1>
            
            <p className="text-lg md:text-xl text-muted-foreground max-w-2xl mx-auto mb-10">
              Enter any computer science topic and get comprehensive notes, explanations, 
              code examples, and quizzes — all generated by advanced AI models.
            </p>
          </motion.div>

          {isLoading ? (
            <LoadingSkeleton
              stage={progress.stage}
              progress={progress.progress}
              message={progress.message}
            />
          ) : (
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: 0.2 }}
            >
              <TopicInput onSubmit={handleTopicSubmit} isLoading={isLoading} />
            </motion.div>
          )}
        </div>
      </section>

      {/* Features Section */}
      {!isLoading && (
        <section className="py-16 px-4">
          <div className="max-w-6xl mx-auto">
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.4 }}
              className="text-center mb-12"
            >
              <h2 className="text-2xl md:text-3xl font-bold text-foreground mb-4">
                Complete Learning Package
              </h2>
              <p className="text-muted-foreground max-w-xl mx-auto">
                Get everything you need to master any topic, generated instantly by AI
              </p>
            </motion.div>
            
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
              {FEATURES.map((feature, index) => (
                <motion.div
                  key={feature.title}
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: 0.5 + index * 0.1 }}
                  className="glass-card-hover rounded-xl p-6 group"
                >
                  <div className="p-3 rounded-xl bg-primary/10 w-fit mb-4 group-hover:bg-primary/20 transition-colors">
                    <feature.icon className="w-6 h-6 text-primary" />
                  </div>
                  <h3 className="text-lg font-semibold text-foreground mb-2">{feature.title}</h3>
                  <p className="text-sm text-muted-foreground">{feature.description}</p>
                </motion.div>
              ))}
              
              {/* CTA Card */}
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 1 }}
                className="glass-card rounded-xl p-6 bg-hero-gradient border border-primary/20 flex flex-col justify-center"
              >
                <h3 className="text-lg font-semibold text-foreground mb-2">Ready to Learn?</h3>
                <p className="text-sm text-muted-foreground mb-4">
                  Enter any topic above to get started with AI-powered learning materials.
                </p>
                <div className="flex items-center gap-2 text-primary font-medium text-sm">
                  <span>Get started</span>
                  <ArrowRight className="w-4 h-4" />
                </div>
              </motion.div>
            </div>
          </div>
        </section>
      )}

      {/* Dataset Sources */}
      {!isLoading && (
        <section className="py-16 px-4 border-t border-border/30">
          <div className="max-w-4xl mx-auto text-center">
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ delay: 1.2 }}
            >
              <p className="text-sm text-muted-foreground mb-4">Powered by leading datasets</p>
              <div className="flex flex-wrap items-center justify-center gap-6 text-xs text-muted-foreground/70">
                <span className="px-3 py-1 rounded-full bg-secondary/50">CodeXGLUE</span>
                <span className="px-3 py-1 rounded-full bg-secondary/50">The Stack</span>
                <span className="px-3 py-1 rounded-full bg-secondary/50">Wikipedia</span>
                <span className="px-3 py-1 rounded-full bg-secondary/50">ELI5</span>
                <span className="px-3 py-1 rounded-full bg-secondary/50">OpenBookQA</span>
                <span className="px-3 py-1 rounded-full bg-secondary/50">BoolQ</span>
              </div>
            </motion.div>
          </div>
        </section>
      )}
    </div>
  );
}
