import { useState, useCallback } from 'react';
import { motion } from 'framer-motion';
import { Sparkles } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { TopicInput } from '@/components/TopicInput';
import { LoadingSkeleton } from '@/components/LoadingSkeleton';
import { runPipeline, type PipelineProgress } from '@/ai/pipeline';
import type { LearningMaterial } from '@/types/learning';
import { toast } from '@/hooks/use-toast';

interface HomeProps {
  onMaterialGenerated: (material: LearningMaterial, topic: string) => void;
}

export function Home({ onMaterialGenerated }: HomeProps) {
  const [isLoading, setIsLoading] = useState(false);
  const [progress, setProgress] = useState<PipelineProgress>({ stage: '', progress: 0, message: '' });
  const navigate = useNavigate();

  const handleTopicSubmit = useCallback(async (topic: string) => {
    setIsLoading(true);
    setProgress({ stage: 'starting', progress: 0, message: 'Initializing AI pipeline...' });

    try {
      const material = await runPipeline(topic, (p) => {
        setProgress(p);
      });

      onMaterialGenerated(material, topic);

      toast({
        title: 'Learning materials ready!',
        description: `Generated comprehensive content for "${topic}"`,
      });

      navigate('/results');
    } catch (error) {
      toast({
        title: 'Generation failed',
        description: error instanceof Error ? error.message : 'An error occurred',
        variant: 'destructive',
      });
    } finally {
      setIsLoading(false);
    }
  }, [navigate, onMaterialGenerated]);

  return (
    <div className="min-h-screen flex flex-col items-center justify-center bg-background py-12 px-4">
      <div className="w-full max-w-2xl">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
          className="text-center mb-8"
        >
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-primary/10 border border-primary/20 mb-6">
            <Sparkles className="w-4 h-4 text-primary" />
            <span className="text-sm text-primary font-medium">AI-Powered Learning</span>
          </div>

          <h1 className="text-4xl md:text-5xl font-bold text-foreground mb-4 leading-tight">
            Learn Any Topic with
            <span className="block text-primary">AI-Generated Content</span>
          </h1>

          <p className="text-lg text-muted-foreground max-w-2xl mx-auto mb-8">
            Enter any computer science topic and get comprehensive notes, explanations,
            and code examples — all generated by advanced AI models.
          </p>
        </motion.div>

        {isLoading ? (
          <LoadingSkeleton
            stage={progress.stage}
            progress={progress.progress}
            message={progress.message}
          />
        ) : (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.2 }}
          >
            <TopicInput onSubmit={handleTopicSubmit} isLoading={isLoading} />
          </motion.div>
        )}
      </div>
    </div>
  );
}
